#! /bin/sh
# Razer Blackwidow Chroma Keyboard Leds daemon init script
### BEGIN INIT INFO
# Provides: 		razer_bcd
# Required-Start:	$network $remote_fs
# Should-Start:		
# Required-Stop:	$network $remote_fs
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description: start/stops razer_bcd
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/razer_bcd
DAEMON_OPTS="--pid-file /var/run/razer_bcd.pid"
FUNCTIONS=/usr/share/razer_bcd/bash_keyboard_functions.sh
NAME="razer_bcd"
DESC="Razer Keyboard daemon"

set -e

test -x $DAEMON || exit 0

# Include razer_bcd defaults if available
if [ -f /etc/default/razer_bcd ] ; then
	. /etc/default/razer_bcd
fi

# Load LSB Functions
. /lib/lsb/init-functions

# Load in the binding and unbinding functions
. $FUNCTIONS

check_for_old_pid_file() {
	if [ -e "/var/run/razer_bcd.pid" ]; then
		# PID FILE EXIST
		current_pid=$(cat /var/run/razer_bcd.pid)
		if ps -p $current_pid > /dev/null; then
			# PID is running
			echo "$NAME is already running. Aborting"
			return 1;
		else
			# PID isn't running. Remove the old PID file
			rm "/var/run/razer_bcd.pid"
		fi
	fi

	return 0;
}


check_for_upstart() {
	if init_is_upstart; then
		exit $1
	fi
}


case "$1" in
  start)
	check_for_upstart 1
	check_for_old_pid_file
	log_daemon_msg "Starting $DESC" "$NAME" || true

	bind_all

	if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/razer_bcd.pid --exec ${DAEMON} -- ${DAEMON_OPTS}; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;
  stop)
	check_for_upstart 0
	log_daemon_msg "Stopping $DESC" "$NAME" || true


	if start-stop-daemon --stop --quiet --pidfile /var/run/razer_bcd.pid; then
	    # Unbind the chromas
	    log_end_msg 0 || true
	    unbind_all

	    # Use the function to remove pid
	    check_for_old_pid_file

	else
	    echo "Daemon isnt running. Or the PID file is incorrect"
	    log_end_msg 1 || true
	fi
	;;
  #reload)
	#
	#	If the daemon can reload its config files on the fly
	#	for example by sending it SIGHUP, do it here.
	#
	#	If the daemon responds to changes in its config file
	#	directly anyway, make this a do-nothing entry.
	#
	# echo "Reloading $DESC configuration files."
	# start-stop-daemon --stop --signal 1 --quiet --pidfile \
	#	/var/run/$NAME.pid --exec $DAEMON
  #;;
  restart|force-reload)
	#
	#	If the "reload" option is implemented, move the "force-reload"
	#	option to the "reload" entry above. If not, "force-reload" is
	#	just the same as "restart".
	#
	check_for_upstart 1
	log_daemon_msg "Restarting $DESC" "$NAME" || true
	
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile /var/run/razer_bcd.pid

	if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/razer_bcd.pid --exec ${DAEMON} -- ${DAEMON_OPTS}; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi

	;;
  status)
	check_for_upstart 1
	status_of_proc -p /var/run/razer_bcd.pid ${DAEMON} ${NAME} && exit 0 || exit $?
	;;
  *)
	log_action_msg "Usage: /etc/init.d/razer_bcd {start|stop|restart|force-reload|status}" || true
	exit 1
	;;
esac

exit 0
