#!/bin/sh
set -e


if [ "$1" = "purge" ]; then
	update-rc.d razer_bcd remove >/dev/null
fi

# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi

if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask razer_bcd.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge razer_bcd.service >/dev/null
		deb-systemd-helper unmask razer_bcd.service >/dev/null
	fi
fi



exit 0
