# SPDX-License-Identifier: GPL-2.0-or-later

obj-m := razerkbd.o razermouse.o razerkraken.o razeraccessory.o razernari.o

razerkbd-y := razerkbd_driver.o razercommon.o razerchromacommon.o compat.o
razermouse-y := razermouse_driver.o razercommon.o razerchromacommon.o compat.o
razerkraken-y := razerkraken_driver.o razercommon.o compat.o
razeraccessory-y := razeraccessory_driver.o razercommon.o razerchromacommon.o compat.o
razernari-y := razernari_driver.o razercommon.o compat.o
