#! /bin/sh
# Razer Blackwidow Chroma Keyboard Leds daemon init script
### BEGIN INIT INFO
# Provides: 		razer_bcd
# Required-Start:	$network $remote_fs
# Should-Start:		
# Required-Stop:	$network $remote_fs
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description: start/stops razer_bcd
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/razer_bcd
BIND=/usr/sbin/razer_blackwidow_chroma_activate_driver.sh
NAME=razer_bcd
DESC=razer_bcd

RAZER_BLACKWIDOW_CHROMA_DEVICES=`ls /sys/bus/hid/devices/ | grep "1532:0203"`

test -x $DAEMON || exit 0
test -x $BIND || exit 0

# Include razer_bcd defaults if available
if [ -f /etc/default/razer_bcd ] ; then
	. /etc/default/razer_bcd
fi

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "
	#start-stop-daemon --start --quiet \
	#	--exec $DAEMON -- --pidfile /var/run/$NAME.pid $DAEMON_OPTS
	#for DEV in $RAZER_BLACKWIDOW_CHROMA_DEVICES
	#do 
	#	if [ -d "/sys/bus/hid/devices/$DEV/input" ]; then
	#		INPUT_DEVS=`ls /sys/bus/hid/devices/$DEV/input`
	#		for INPUT_DEV in $INPUT_DEVS
	#		do
	#			MOUSE=`ls /sys/bus/hid/devices/$DEV/input/$INPUT_DEV/ | grep "mouse"`
	#			if [ $MOUSE ]; then
	#				#echo "Found Razer LED Device : $DEV"
	#				echo "Activating Driver"
	#				echo -n "$DEV" > /sys/bus/hid/drivers/hid-generic/unbind 2> /dev/null
	#				#echo $?
	#				echo -n "$DEV" > /sys/bus/hid/drivers/razerkbd/bind 2> /dev/null
	#				#echo $?
	#			fi
	#		done
	#	fi
	#done

	$BIND
	$DAEMON
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	#start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid --oknodo
	PID=$(pidof $DAEMON)
	case $PID in "");;*)
		kill -INT $PID
	;;esac
	echo "$NAME."
	;;
  #reload)
	#
	#	If the daemon can reload its config files on the fly
	#	for example by sending it SIGHUP, do it here.
	#
	#	If the daemon responds to changes in its config file
	#	directly anyway, make this a do-nothing entry.
	#
	# echo "Reloading $DESC configuration files."
	# start-stop-daemon --stop --signal 1 --quiet --pidfile \
	#	/var/run/$NAME.pid --exec $DAEMON
  #;;
  restart|force-reload)
	#
	#	If the "reload" option is implemented, move the "force-reload"
	#	option to the "reload" entry above. If not, "force-reload" is
	#	just the same as "restart".
	#
	echo -n "Restarting $DESC: "
	start-stop-daemon --stop --quiet --pidfile \
		/var/run/$NAME.pid --exec $DAEMON --oknodo
	sleep 1
	start-stop-daemon --start --quiet --pidfile \
		/var/run/$NAME.pid --exec $DAEMON -- --pidfile /var/run/$NAME.pid $DAEMON_OPTS
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	# echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
